// $ROUTER_ROUTE_TYPE$ - $ROUTER_ROUTE_TITLE$
// $ROUTER_ROUTE_DESCRIPTION$
router.$ROUTER_ROUTE_TYPE_CALL$('/$ROUTER_ROUTE_CAT_NAME$$ROUTER_ROUTE_PARAM_FIELD$'$ROUTER_ROUTE_MIDDLEWARE_CALL$,$ROUTER_ROUTE_SANITIZER_CALL$$ROUTER_ROUTE_VALIDATOR_CALL$ $ROUTER_ROUTE_CONTROLLER_CALL$);