# Migrations
MIGRATION_UP = "$MIGRATION_UP$"

MIGRATION_DOWN = "$MIGRATION_DOWN$"

MIGRATION_TABLE_NAME = "$MIGRATION_TABLE_NAME$"

MIGRATION_FIELD_NAME = "$MIGRATION_FIELD_NAME$"

MIGRATION_FIELD_TYPE = "$MIGRATION_FIELD_TYPE$"

MIGRATION_FIELD_PLACEHOLDER = "$MIGRATION_FIELD_PLACEHOLDER$"

MIGRATION_IS_NULLABLE = "$MIGRATION_IS_NULLABLE$"

MIGRATION_DEFAULT = "$MIGRATION_DEFAULT$"

MIGRATION_DEFAULT_VALUE = "$MIGRATION_DEFAULT_VALUE$"

MIGRATION_REFERENCE_PLACEHOLDER = "$MIGRATION_REFERENCE_PLACEHOLDER$"

MIGRATION_REFERENCE_FIELD_NAME = "$MIGRATION_REFERENCE_FIELD_NAME$"

MIGRATION_REFERENCE_FIELD_TARGET = "$MIGRATION_REFERENCE_FIELD_TARGET$"

# Models
MODEL_NAME = "$MODEL_NAME$"

MODEL_FIELDS = "$MODEL_FIELDS$"

MODEL_FIELD_NAME = "$MODEL_FIELD_NAME$"

MODEL_FIELD_TYPE = "$MODEL_FIELD_TYPE$"

# Router
ROUTER_MIDDLEWARE_IMPORTS = "$ROUTER_MIDDLEWARE_IMPORTS$"

ROUTER_MIDDLEWARE_IMPORT_NAME = "$ROUTER_MIDDLEWARE_IMPORT_NAME$"

ROUTER_SANITIZER_IMPORTS = "$ROUTER_SANITIZER_IMPORTS$"

ROUTER_REQUEST_IMPORTS = "$ROUTER_REQUEST_IMPORTS$"

ROUTER_CONTROLLER_IMPORTS = "$ROUTER_CONTROLLER_IMPORTS$"

ROUTER_ROUTES = "$ROUTER_ROUTES$"

# Sanitizer
SANITIZER_MIDDLEWARES = "$SANITIZER_MIDDLEWARES$"

# Validators
VALIDATOR_MIDDLEWARES = "$VALIDATOR_MIDDLEWARES$"

# Controllers
CONTROLLER_MODEL_IMPORTS = "$CONTROLLER_MODEL_IMPORTS$"

CONTROLLER_ACTION_IMPORTS = "$CONTROLLER_ACTION_IMPORTS$"

CONTROLLER_DATA_FROM_REQUEST_IMPORTS = "$CONTROLLER_DATA_FROM_REQUEST_IMPORTS$"

CONTROLLER_PLACEHOLDER = "$CONTROLLER_PLACEHOLDER$"

# DataTransfertObject
DTO_PLACEHOLDER = "$DTO_PLACEHOLDER$"

# Actions
ACTION_PLACEHOLDER = "$ACTION_PLACEHOLDER$"

ACTION_MODEL_IMPORTS = "$ACTION_MODEL_IMPORTS$"

ACTION_DATA_IMPORTS = "$ACTION_DATA_IMPORTS$"
