# Migrations
MIGRATION_UP = "$MIGRATION_UP$"

MIGRATION_DOWN = "$MIGRATION_DOWN$"

MIGRATION_TABLE_NAME = "$MIGRATION_TABLE_NAME$"

# Models
MODEL_NAME = "$MODEL_NAME$"

MODEL_FIELDS = "$MODEL_FIELDS$"

# Router
ROUTER_SANITIZER_IMPORT = "$ROUTER_SANITIZER_IMPORT$"

ROUTER_REQUEST_IMPORT = "$ROUTER_REQUEST_IMPORT$"

ROUTER_CONTROLLER_IMPORT = "$ROUTER_CONTROLLER_IMPORT$"

ROUTER_ROUTES = "$ROUTER_ROUTES$"

# Sanitizer
SANITIZER_MIDDLEWARES = "$SANITIZER_MIDDLEWARES$"

# Validators
VALIDATOR_MIDDLEWARES = "$VALIDATOR_MIDDLEWARES$"

# Controllers
CONTROLLER_MODEL_IMPORT = "$CONTROLLER_MODEL_IMPORT$"

CONTROLLER_ACTION_IMPORT = "$CONTROLLER_ACTION_IMPORT$"

CONTROLLER_DATA_FROM_REQUEST_IMPORT = "$CONTROLLER_DATA_FROM_REQUEST_IMPORT$"

CONTROLLER_PLACEHOLDER = "$CONTROLLER_PLACEHOLDER$"

# DataTransfertObject
DTO_PLACEHOLDER = "$DTO_PLACEHOLDER$"

# Actions
ACTION_PLACEHOLDER = "$ACTION_PLACEHOLDER$"

ACTION_MODEL_IMPORT = "$ACTION_MODEL_IMPORT$"

ACTION_DATA_IMPORT = "$ACTION_DATA_IMPORT$"
