# Migrations
MIGRATION_UP = "$MIGRATION_UP$"

MIGRATION_DOWN = "$MIGRATION_DOWN$"

MIGRATION_TABLE_NAME = "$MIGRATION_TABLE_NAME$"

MIGRATION_FIELD_NAME = "$MIGRATION_FIELD_NAME$"

MIGRATION_FIELD_TYPE = "$MIGRATION_FIELD_TYPE$"

MIGRATION_FIELD_PLACEHOLDER = "$MIGRATION_FIELD_PLACEHOLDER$"

MIGRATION_IS_NULLABLE = "$MIGRATION_IS_NULLABLE$"

MIGRATION_DEFAULT = "$MIGRATION_DEFAULT$"

MIGRATION_DEFAULT_VALUE = "$MIGRATION_DEFAULT_VALUE$"

MIGRATION_REFERENCE_PLACEHOLDER = "$MIGRATION_REFERENCE_PLACEHOLDER$"

MIGRATION_REFERENCE_FIELD_NAME = "$MIGRATION_REFERENCE_FIELD_NAME$"

MIGRATION_REFERENCE_FIELD_TARGET = "$MIGRATION_REFERENCE_FIELD_TARGET$"

# Models
MODEL_NAME = "$MODEL_NAME$"

MODEL_FIELDS = "$MODEL_FIELDS$"

MODEL_FIELD_NAME = "$MODEL_FIELD_NAME$"

MODEL_FIELD_TYPE = "$MODEL_FIELD_TYPE$"

# Router
ROUTER_MIDDLEWARE_IMPORTS = "$ROUTER_MIDDLEWARE_IMPORTS$"

ROUTER_MIDDLEWARE_IMPORT_NAME = "$ROUTER_MIDDLEWARE_IMPORT_NAME$"

ROUTER_SANITIZER_IMPORTS = "$ROUTER_SANITIZER_IMPORTS$"

ROUTER_SANITIZER_IMPORT_FILE_NAME = "$ROUTER_SANITIZER_IMPORT_FILE_NAME$"

ROUTER_SANITIZER_IMPORT_SANITIZER_NAME = "$ROUTER_SANITIZER_IMPORT_SANITIZER_NAME$"

ROUTER_VALIDATOR_IMPORTS = "$ROUTER_VALIDATOR_IMPORTS$"

ROUTER_VALIDATOR_IMPORT_FILE_NAME = "$ROUTER_VALIDATOR_IMPORT_FILE_NAME$"

ROUTER_VALIDATOR_IMPORT_VALIDATOR_NAME = "$ROUTER_VALIDATOR_IMPORT_VALIDATOR_NAME$"

ROUTER_CONTROLLER_IMPORTS = "$ROUTER_CONTROLLER_IMPORTS$"

ROUTER_CONTROLLER_IMPORT_FILE_NAME = "$ROUTER_CONTROLLER_IMPORT_FILE_NAME$"

ROUTER_CONTROLLER_IMPORT_SANITIZER_NAME = "$ROUTER_CONTROLLER_IMPORT_SANITIZER_NAME$"

ROUTER_ROUTES = "$ROUTER_ROUTES$"

ROUTER_ROUTE_TYPE = "$ROUTER_ROUTE_TYPE$"

ROUTER_ROUTE_TITLE = "$ROUTER_ROUTE_TITLE$"

ROUTER_ROUTE_DESCRIPTION = "$ROUTER_ROUTE_DESCRIPTION$"

ROUTER_ROUTE_TYPE_CALL = "$ROUTER_ROUTE_TYPE_CALL$"

ROUTER_ROUTE_CAT_NAME = "$ROUTER_ROUTE_CAT_NAME$"

ROUTER_ROUTE_PARAM_FIELD = "$ROUTER_ROUTE_PARAM_FIELD$"

ROUTER_ROUTE_PARAM_FIELD = "$ROUTER_ROUTE_PARAM_FIELD$"

ROUTER_ROUTE_PARAM_NAME = "$ROUTER_ROUTE_PARAM_NAME$"

ROUTER_ROUTE_MIDDLEWARE_CALL = "$ROUTER_ROUTE_MIDDLEWARE_CALL$"

ROUTER_ROUTE_MIDDLEWARE_NAME = "$ROUTER_ROUTE_MIDDLEWARE_NAME$"

ROUTER_ROUTE_CONTROLLER_CALL = "$ROUTER_ROUTE_CONTROLLER_CALL$"

# Sanitizer
SANITIZER_MIDDLEWARES = "$SANITIZER_MIDDLEWARES$"

SANITIZER_MIDDLEWARE_NAME = "$SANITIZER_MIDDLEWARE_NAME$"

SANITIZER_MIDDLEWARE_RULES = "$SANITIZER_MIDDLEWARE_RULES$"

SANITIZER_MIDDLEWARE_RULE_NAME = "$SANITIZER_MIDDLEWARE_RULE_NAME$"

SANITIZER_MIDDLEWARE_RULE_VALUE = "$SANITIZER_MIDDLEWARE_RULE_VALUE$"

# Validators
VALIDATOR_MIDDLEWARES = "$VALIDATOR_MIDDLEWARES$"

VALIDATOR_MIDDLEWARE_NAME = "$VALIDATOR_MIDDLEWARE_NAME$"

VALIDATOR_MIDDLEWARE_RULES = "$VALIDATOR_MIDDLEWARE_RULES$"

VALIDATOR_MIDDLEWARE_RULE_NAME = "$VALIDATOR_MIDDLEWARE_RULE_NAME$"

VALIDATOR_MIDDLEWARE_RULE_VALUE = "$VALIDATOR_MIDDLEWARE_RULE_VALUE$"

# Controllers
CONTROLLER_MODEL_IMPORTS = "$CONTROLLER_MODEL_IMPORTS$"

CONTROLLER_MODEL_IMPORT_MODEL_NAME = "$CONTROLLER_MODEL_IMPORT_MODEL_NAME$"

CONTROLLER_MODEL_IMPORT_FILE_NAME = "$CONTROLLER_MODEL_IMPORT_FILE_NAME$"

CONTROLLER_ACTION_IMPORTS = "$CONTROLLER_ACTION_IMPORTS$"

CONTROLLER_DTO_IMPORTS = "$CONTROLLER_DTO_IMPORTS$"

CONTROLLER_DTO_IMPORT_FILE_NAME = "$CONTROLLER_DTO_IMPORT_FILE_NAME$"

CONTROLLER_DTO_IMPORT_DTO_NAMES = "$CONTROLLER_DTO_IMPORT_DTO_NAMES$"

CONTROLLER_ACTION_IMPORT_FILE_NAME = "$CONTROLLER_ACTION_IMPORT_FILE_NAME$"

CONTROLLER_ACTION_IMPORT_ACTION_NAMES = "$CONTROLLER_ACTION_IMPORT_ACTION_NAMES$"

CONTROLLER_PLACEHOLDER = "$CONTROLLER_PLACEHOLDER$"

CONTROLLER_CONTROLLER_NAME = "$CONTROLLER_CONTROLLER_NAME$"

CONTROLLER_CONTROLLER_DTO_FUNC_NAME = "$CONTROLLER_CONTROLLER_DTO_FUNC_NAME$"

CONTROLLER_CONTROLLER_DTO_STRUC_NAME = "$CONTROLLER_CONTROLLER_DTO_STRUC_NAME$"

CONTROLLER_CONTROLLER_ACTION_NAME = "$CONTROLLER_CONTROLLER_ACTION_NAME$"

CONTROLLER_CONTROLLER_ACTION_RET_TYPE = "$CONTROLLER_CONTROLLER_ACTION_RET_TYPE$"

CONTROLLER_CONTROLLER_SUCESS_RES = "$CONTROLLER_CONTROLLER_SUCESS_RES$"

CONTROLLER_CONTROLLER_DB_ERROR_RES = "$CONTROLLER_CONTROLLER_DB_ERROR_RES$"

CONTROLLER_CONTROLLER_DTO_ERROR_RES = "$CONTROLLER_CONTROLLER_DTO_ERROR_RES$"

# DataTransfertObject
DTO_RAW_IMPORT_PLACEHOLDER = "$DTO_RAW_IMPORT_PLACEHOLDER$"

DTO_PLACEHOLDER = "$DTO_PLACEHOLDER$"

DTO_STRUC_NAME = "$DTO_STRUC_NAME$"

DTO_ASYNC_PLACEHOLDER = "$DTO_ASYNC_PLACEHOLDER$"

DTO_STRUC_FIELDS = "$DTO_STRUC_FIELDS$"

DTO_STRUC_FIELD_NAME = "$DTO_STRUC_FIELD_NAME$"

DTO_STRUC_FIELD_TYPE = "$DTO_STRUC_FIELD_TYPE$"

DTO_FUNC_NAME = "$DTO_FUNC_NAME$"

DTO_FUNC_RETRIEVES = "$DTO_FUNC_RETRIEVES$"

DTO_FUNC_RETRIEVE_NAME = "$DTO_FUNC_RETRIEVE_NAME$"

DTO_FUNC_RETRIEVE_VALUE = "$DTO_FUNC_RETRIEVE_VALUE$"

DTO_FUNC_RETRIEVE_VALUE_FROM_BODY_NAME = "$DTO_FUNC_RETRIEVE_VALUE_FROM_BODY_NAME$"

DTO_FUNC_RETRIEVE_VALUE_FROM_PARAMS_NAME = "$DTO_FUNC_RETRIEVE_VALUE_FROM_PARAMS_NAME$"

DTO_RAW_IMPORT_VALUE = "$DTO_RAW_IMPORT_VALUE$"

# Actions
ACTION_PLACEHOLDER = "$ACTION_PLACEHOLDER$"

ACTION_MODEL_IMPORTS = "$ACTION_MODEL_IMPORTS$"

ACTION_DTO_IMPORTS = "$ACTION_DTO_IMPORTS$"

ACTION_DTO_IMPORT_FILE_NAME = "$ACTION_DTO_IMPORT_FILE_NAME$"

ACTION_DTO_IMPORT_DTO_NAME = "$ACTION_DTO_IMPORT_DTO_NAME$"

ACTION_MODEL_IMPORT_FILE_NAME = "$ACTION_MODEL_IMPORT_FILE_NAME$"

ACTION_MODEL_IMPORT_MODEL_NAME = "$ACTION_MODEL_IMPORT_MODEL_NAME$"

ACTION_ACTION_NAME = "$ACTION_ACTION_NAME$"

ACTION_ACTION_RETURN_TYPE = "$ACTION_ACTION_RETURN_TYPE$"

ACTION_DTO_TYPE = "$ACTION_DTO_TYPE$"

ACTION_MODEL_NAME = "$ACTION_MODEL_NAME$"

ACTION_CUSTOM_RET_TYPE = "$ACTION_CUSTOM_RET_TYPE$"