export const $CONTROLLER_CONTROLLER_NAME$ = $DTO_ASYNC_PLACEHOLDER$(req: Request, res: Response) => {
$CONTROLLER_CONTROLLER_DTO_BLOCK_PLACE$    let resDB = await $CONTROLLER_CONTROLLER_ACTION_NAME$($CONTROLLER_CONTROLLER_DTO_VAR_NAME$);
    if (resDB instanceof ErrorDB) {
        $CONTROLLER_CONTROLLER_DB_ERROR_RES$
        return;
    }

    $CONTROLLER_CONTROLLER_SUCESS_RES$
};

$CONTROLLER_PLACEHOLDER$